spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev #dev环境
  application:
    name: microservicecloud-config-zxs-dev
eureka:
  client: 
    service-url: 
       defaultZone: http://eureka-dev:7001/eureka/
---
server:
  port: 8202
spring:
  profiles: test  #测试环境
  application:
    name: micoservicecloud-config-zxs-test
eureka:
  client: 
    service-url: 
       defaultZone: http://eureka-test:7002/eureka/
#请保存为utf-8格式